### ISSUE TITLE
The title in the 3D MPR needs to be changed, not SlicerQREADS

### ISSUE THREAD

**Issue by jcfr** [KitwareMedical/SlicerQReads#102]
Originally report by @spycolyf

**Comment by jcfr** [comment]
While the data is loading, the title bar is to to this:

![image](https://user-images.githubusercontent.com/219043/116348060-5d3e0280-a7bb-11eb-9877-ce5952b13928.png)

What should be displayed instead ? Is `CMRN` the name of the application ?

**Comment by spycolyf** [comment]
Change does not apply to this public version public version.
