### ISSUE TITLE
Add Distance measurement tool

### ISSUE THREAD

**Issue by jcfr** [KitwareMedical/SlicerQReads#21]

**Comment by spycolyf** [comment]
Here is my desired schedule...

ASAP ................................... (Priority 3a) Update image information integated in toolbar #59
ASAP ................................... (Priority 3b) Update icon associated with the application #60
Friday April 9th ............... (Priority 4) Distance measurement tool #21
Tuesday April 13th ........ (Priority 5) Reset button #53
Thursday April 15th ...... (Priority 6) More QREADS-like Pan and Zoom Mouse Interaction #7
Friday April 16th ............ (Priority 7) Eliminate unnecessary widgets (see last updated comment) #33
Tuesday April 19th ........ (Priority 8) Increase zoom presets dropdown font size #37

**Comment by spycolyf** [comment]
I will do this.

**Comment by jcfr** [comment]
Suggested approach:
* Associated one node per viewer
* Configure in which viewer the display node is visible
* The show/hide button will toggle visibility of all three nodes

**Comment by spycolyf** [comment]
Done by Doug in another branch to be merged,

**Comment by spycolyf** [comment]
Associate with branch and do pull request
