### ISSUE TITLE
Ensure Gradient is applied to toolbar

### ISSUE THREAD

**Issue by jcfr** [KitwareMedical/SlicerQReads#25]
Suggestion from @spycolyf :

> The gradient doesn’t seem on the qMRMLWidget, but works on qFrame.
> Maybe we can place a qFrame widget in the qMRMLWidget and all controls inside of the qFrame.

**Comment by spycolyf** [comment]
@jcfr Is qMRMTWidget required for use in Slicer? Could we use a widget that will display the gradient background? Or could imbed my ui, with a qFrame containing all other widgets, into a qMRMLWidget?

**Comment by sjh26** [comment]
You can layer widgets and set their background as transparent to allow for gradients to come up /across from different widgets.

**Comment by spycolyf** [comment]
Thanks @sjh26

**Comment by spycolyf** [comment]
@jcfr, do you think this will work in Slicer?

**Comment by jcfr** [comment]
I will investigate and report back.

**Comment by jcfr** [comment]
For future reference:

![image](https://user-images.githubusercontent.com/219043/107283344-485a9a00-6a2a-11eb-9a5c-b130e928cdbe.png)
