### ISSUE TITLE
Eliminate pop-up toolbar and move sliders to the bottom

### ISSUE THREAD

**Issue by spycolyf** [KitwareMedical/SlicerQReads#33]
@jcfr

1) Hide popup toolbar and only keep the sliders.
2) Keep the toolbar in the lower right 3D graphics quadrant.
3) Move the sliders to the bottom

**Comment by spycolyf** [comment]
More specifically, eliminate the following dropdown menus ONLY,

![Screen Shot 2021-03-23 at 11 35 44 AM](https://user-images.githubusercontent.com/74066160/112185545-545f7d00-8bce-11eb-8990-b041f4e295e9.png)
![Screen Shot 2021-03-23 at 11 35 59 AM](https://user-images.githubusercontent.com/74066160/112185547-545f7d00-8bce-11eb-9334-1861b4b737bd.png)
![Screen Shot 2021-03-23 at 11 38 20 AM](https://user-images.githubusercontent.com/74066160/112185548-54f81380-8bce-11eb-8d64-ae271cf5f51b.png)

**Comment by spycolyf** [comment]
That last one is very important because there is a bug selecting "Edit current volume" eliminates the QREADS toolbar and you can't return to the QREADS toolbar. Thanks.

**Comment by jcfr** [comment]
To avoid confusion, I suggest we simply hide popup toolbar and only keep the sliders.

**Comment by spycolyf** [comment]
Let's go ahead and hide popup toolbar and only keep the sliders. That will be fine. 

The only functions I likes were these:

![image](https://user-images.githubusercontent.com/74066160/114632092-86bb4200-9c83-11eb-98eb-9149498895b4.png)

Maybe we can put these in the tools section of the QREADS toolbar.
