### ISSUE TITLE
(Priority 1) Brighter Reference Lines with Black Image Backgrounds (see last updated comment)

### ISSUE THREAD

**Issue by spycolyf** [KitwareMedical/SlicerQReads#34]

**Comment by spycolyf** [comment]
Let's try 990000, 009900 and 000099 to brighten the lines.

**Comment by jcfr** [comment]
As an exercise, I suggest you:
- create a branch called `34-update-viewer-colors`
- update this section of the code accordingly: https://github.com/KitwareMedical/SlicerQReads/blob/52e84ddc4c6d637f72b350c7061aad693f430f28/Modules/Scripted/QReads/QReads.py#L336-L340
- re-build the target `CopySlicerPythonScriptFiles`:

  ```
  cd C:\path\to\SQR-b\Slicer-build
  cmake --build . -config Release --target CopySlicerPythonScriptFiles
  ```
- run the application to confirm the colors are the expected one
- publish the branch and create a pull request

**Comment by jcfr** [comment]
@spycolyf Please annotate this image to make it clear which color need to be changed to what ? 

![image](https://user-images.githubusercontent.com/219043/110549793-95e92600-8100-11eb-868f-38938bd4c61d.png)

**Comment by spycolyf** [comment]
Here it is JC...

![BGBlack](https://user-images.githubusercontent.com/74066160/110561049-9edff480-810c-11eb-8b63-8c888bd0d98c.JPG)

**Comment by spycolyf** [comment]
... also, could you increase the size of the scroll bars so that they are a little more visible? Thanks.

**Comment by spycolyf** [comment]
Done. Let me know what you think. Thanks.

**Comment by spycolyf** [comment]
@jcfr, I've resized the QREADS toolbar and created new icons. I tried replacing the icons in the latest release that I downloaded from GitHub rebuilding it. I received errors. Don't know what I did wrong.

@jcfr, the icons and Toolbar are uploaded and here are the links. Could you have a look? Thanks.


From: Jean-Christophe Fillion-Robin ***@***.***>
Sent: Tuesday, March 9, 2021 4:56 PM
To: KitwareMedical/SlicerQReads ***@***.***>
Cc: Porter, Douglas V., M.S. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [KitwareMedical/SlicerQReads] (Priority 2) Brighter Reference Lines with Black Image Backgrounds (#34)


@spycolyf<https://github.com/spycolyf> Please annotate this image to make it clear which color need to be changed to what ?

[image]<https://user-images.githubusercontent.com/219043/110549793-95e92600-8100-11eb-868f-38938bd4c61d.png>

**Comment by spycolyf** [comment]
Actually and thin view port border would be great. Check this out...

![SlicerQRBrighterReferenceMarkers](https://user-images.githubusercontent.com/74066160/112188708-38110f80-8bd1-11eb-8d5c-54c3e850b1d3.JPG)

DO THIS ONLY IF IT TAKES LESS TIME: OTHERWISE THE TOP SROLL BAR COLOR IS GREAT. 

Which ever takes the least time to do.

**Comment by jcfr** [comment]
For reference:

| Before | After |
|--|--|
| ![image](https://user-images.githubusercontent.com/219043/112788666-6192c680-9029-11eb-8836-bf00ca520542.png) |  ![image](https://user-images.githubusercontent.com/219043/112788628-4922ac00-9029-11eb-8b4a-ce66029bb50f.png) |

**Comment by spycolyf** [comment]
Great!
