### ISSUE TITLE
Make the text in upper right of each image panel WHITE

### ISSUE THREAD

**Issue by spycolyf** [KitwareMedical/SlicerQReads#35]
Make the text in upper right of each image panel white. The “A: 129.0000mm” value below needs to be easier to see. In other panels, it’s even harder to see.

![SliceLocation](https://user-images.githubusercontent.com/74066160/109067773-94f1d680-76b4-11eb-909d-a0cac10721aa.png)

**Comment by jcfr** [comment]
| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/219043/109773687-7d8f7d80-7bcd-11eb-9b13-f9a3d36899b5.png)| ![image](https://user-images.githubusercontent.com/219043/109773660-76686f80-7bcd-11eb-9044-231b1652b4e5.png) |
