### ISSUE TITLE
Increase zoom presets dropdown font size

### ISSUE THREAD

**Issue by spycolyf** [KitwareMedical/SlicerQReads#37]

**Comment by spycolyf** [comment]
Done by Doug in A branch to be merged

**Comment by jcfr** [comment]
See https://github.com/KitwareMedical/SlicerQReads/tree/DougMayoSlicerQREADSBranch

**Comment by spycolyf** [comment]
Hello JC, I’m starting to split that branch into separate branches that address the individual issues. Shall I continue or shall I clean up the DougMayoSlicerQREADSBranch?

**Comment by jcfr** [comment]
> Shall I continue or shall I clean up the DougMayoSlicerQREADSBranch?

No need for that. I will post an update here in  20 minutes or so when I am done creating the different pull requests.

Then, I will post comment on each pull requests

**Comment by spycolyf** [comment]
OK, I just read this. Please see my pull requests. I wanted to do this the correct way and DougMayoSlicerQREADSBranch was incomplete.
