### ISSUE TITLE
Application fails to start looking up for Splash screen

### ISSUE THREAD

**Issue by jcfr** [KitwareMedical/SlicerQReads#43]
reported by @lxw06:

Following the integration of https://github.com/KitwareMedical/SlicerQReads/pull/41, application seems to fail to start:

![image](https://user-images.githubusercontent.com/219043/109554552-6011c500-7aa2-11eb-8d2f-ff626ce8b75d.png)

**Comment by jcfr** [comment]
@lxw06 What is the content of the files `SlicerQReadsLauncherSettings.ini` and `SlicerQReadsLauncherSettingsToInstall.ini` found in the build directory ? 

They should have the `--no-splash ` argument already specified.

For example:

```
[...]

[Application]
path=<APPLAUNCHER_DIR>/bin/./SlicerQReadsApp-real
arguments=--no-splash 
name=SlicerQReads

[...]
```

**Comment by Lxw06** [comment]
```
[Application]
path=<APPLAUNCHER_DIR>/bin/SlicerQReadsApp-real.exe
arguments=
name=SlicerQReads
revision=29687
organizationDomain=mayoclinic.org
organizationName=Mayo Clinic
```
-----------------------------------------------------------
I will get the code and rebuild it again.

**Comment by Lxw06** [comment]
I will modify it like: arguments=--no-splash
 and retest it.

**Comment by Lxw06** [comment]
after modified the arguments, the app can be launched, but the splash image is still showing.

**Comment by jcfr** [comment]
You do not need to modify the settings yourself.

**Comment by jcfr** [comment]
If you try to run `SlicerQReads.exe` passing `--no-splash`, is the splash screen visible ?

**Comment by Lxw06** [comment]
```
SlicerQReads.exe --python-code --no-splash "folder='S:\VTKTest\QREADS3DTest\TestImages'; import os; slicer.util.loadVolume(folder + '\' + os.listdir(folder)[0], {'singleFile': False})"
```

nothing is showing

**Comment by jcfr** [comment]
Try this instead:

```
SlicerQReads.exe --no-splash --python-code  "folder='S:\VTKTest\QREADS3DTest\TestImages'; import os; slicer.util.loadVolume(folder + '\' + os.listdir(folder)[0], {'singleFile': False})"
```

**Comment by jcfr** [comment]
After doing a clean build on Linux, I am not able to reproduce the problem. I will do a clean build on Windows as well to check.
