### ISSUE TITLE
W/L Reset button

### ISSUE THREAD

**Issue by spycolyf** [KitwareMedical/SlicerQReads#53]
I recently discovered in SlicerQREADS, that when in W/L mode, pressing the left and right buttons simultaneously resets the W/L. Let's assign that function to the reset button since the code already exists the W/L left and right button event handler.

**Comment by spycolyf** [comment]
@jcfr 

I recently discovered that when in W/L mode, pressing the left and right buttons simultaneously resets the W/L. To cut development time, let’s assign that function to the reset button since the code already exists the W/L toggle function.

**Comment by jcfr** [comment]
For sake of correctness, the action resetting the window level is `vtkCommand::LeftButtonDoubleClickEvent`

https://github.com/Slicer/Slicer/blob/c24fc171e55c36ba1911d1adcb306b4c52b9a0ad/Libs/MRML/DisplayableManager/vtkMRMLWindowLevelWidget.cxx#L91

**Comment by jcfr** [comment]
It is equivalent to call `vtkMRMLScalarVolumeDisplayNode::AutoWindowLevelOn()`
