### ISSUE TITLE
(Priority 3a) Update image information integated in toolbar

### ISSUE THREAD

**Issue by jcfr** [KitwareMedical/SlicerQReads#59]
from @jcfr: 

> > I'm not seeing the demographics in the title bar. Here's what I see...
> 
> Make sure to re-run the target as explained in the email.
> 
> Code is the following:
> 
> https://github.com/KitwareMedical/SlicerQReads/blob/fff532db17159791fc5917b2ca72b92f44312a1d/Modules/Scripted/QReads/QReads.py#L224-L235
> 
> > re: icon 
> 
> Thanks, will update when back at the computer tomorrow morning.
> 
> 
> > Remove the version number, and make it more like QREADS title bar...
> 
> How does that look:
> 
> ```diff
> -SlicerQReads X.Y.Z YYYY-MM-DD {PatientName} - {PatientID} - {StudyDescription} - {SeriesDescription}
> +SlicerQReads\t Patient Number: {PatientID}\t Patient Name: {PatientName}\t Study Description:{StudyDescription}\t Series Description: {SeriesDescription}
> ```

-------

from @spycolyf 

> Looks good: Remove the SlicerQREADS name and include only the icon and the Patient info as seen in the Picture above. This one is the MPR icon and when we do the Fusion one, a Fusion icon will be used. To have SlicerQREADS on both will be confusing.

-------

from @spycolyf : 

> Here is a Mock up of the title bar 

> ![SlicerTitleBarMissingDemographics](https://user-images.githubusercontent.com/74066160/113080501-a3904980-919c-11eb-948b-0c4a663e9120.PNG)

**Comment by spycolyf** [comment]
Hell JC,

I performed a full git Bash and build and still don’t see the patient demographics in the title bar. Do you want me to try to make the changes to QREADS.py on my side? What is the best way to do that? Shall I make the changes in the sqr gitbash download folder or the sqr-r release build folder?

**Comment by jcfr** [comment]
After opening Git Bash, and running the command:

```
git log -n1
```

Could you confirm you get output similar to this:

```
commit 1dc2309afdecac63ae8d7672b9dc870e85ce77df (HEAD -> master, origin/master)
Author: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
Date:   Fri Apr 2 14:22:54 2021 -0400

    ENH: Update Window/Level icon
    
    Fixes #57
    
    Co-authored-by: Doug Porter <dporter@mayo.edu>
```

> Do you want me to try to make the changes to QREADS.py on my side?

Since the changes have already been implemented, independently modifying the file would not make sense.

After rebuilding, could you confirm that the file `lib/SlicerQReads-4.13/qt-scripted-modules/QReads.py` located in the build directory also contain the relevant changes ? (see https://github.com/KitwareMedical/SlicerQReads/issues/59#issue-849390276)

**Comment by spycolyf** [comment]
OK Thanks!

**Comment by spycolyf** [comment]
Sorry, I'm still doing those 14hour intense days. Finally got a break. 

Yes, I get that output exactly

**Comment by spycolyf** [comment]
but, I cannot find the changes to QREADS.py. I can't even find the string "PatientName"

**Comment by spycolyf** [comment]
OK, I do see the changes in the Build, but not the Package.

**Comment by spycolyf** [comment]
JC I'm going to do a fresh build. I may have messed something up. I have so much going on. I'll let you know.

**Comment by spycolyf** [comment]
Ok, I was looking in the wrong Package on a different PC. So yes, the QREADS.py file in the Package contains those changes. My Package folder name is C:\SlicerQREADS-Build_4-5-2021\lib\SlicerQReads-4.13\qt-scripted-module. the qreads.py file is dated 4/3/2021 3:02 PM. 

... and the title bar is not showing the patient demographics.

Is there anything I can do on my end?

**Comment by jcfr** [comment]
> the title bar is not showing the patient demographics. 
> Is there anything I can do on my end?

If I understand correctly, after following  instructions reported above in https://github.com/KitwareMedical/SlicerQReads/issues/59#issuecomment-813537198, you still do not see information in the toolbar ?

**Comment by spycolyf** [comment]
I tried increase the delay update time to 10 seconds, but that did not work. 

      slicer.util.mainWindow().windowTitle = "%s - %s" % (
        slicer.util.mainWindow().windowTitle,
        "CMRN: {PatientID}     Patient Name: {PatientName}     Study: {StudyDescription}     Series: {SeriesDescription}".format(**values))

    # Delay update to ensure images are rendered
    qt.QTimer.singleShot(10000, _update)

**Comment by jcfr** [comment]
Two things to check:

1. Are the relevant changes also in the file contain in the build tree  (for detailed see https://github.com/KitwareMedical/SlicerQReads/issues/59#issuecomment-813537198)? 
2. Are there  any errors reported  in the python interactor (Menu -> View -> Python Interactor) ?

**Comment by jcfr** [comment]
From  @spycolyf  (copied from https://discourse.slicer.org/t/slicerqr-development/15954/103?u=jcfr):

> Yes, the `QREADS.py` file in the Package contains those changes. My Package folder name is `C:\SlicerQREADS-Build_4-5-2021\lib\SlicerQReads-4.13\qt-scripted-module`. the `qreads.py`" file is dated 4/3/2021 3:02 PM. Also, the git log -n1 command shows the result expected. Is there anything else to check?
> 
> I tried changing the wait time to 10000 and that did not work.
> 
> `qt.QTimer.singleShot(10000, _update)`

**Comment by jcfr** [comment]
If you add the following print statements [here](https://github.com/KitwareMedical/SlicerQReads/blob/1dc2309afdecac63ae8d7672b9dc870e85ce77df/Modules/Scripted/QReads/QReads.py#L232):

```
print("*" * 40)
print(values)
print("*" * 40)
```

What do you see in the python interactor ? 


------

> Package contains those changes

When you mention `Package`, what do you exactly mean ? 

To clarify, there are three locations to consider:

1. Source tree
2. Build tree
3. Installed application

**Comment by spycolyf** [comment]
OK yes, I meant the result of the "Package" instructions in the Build.md file. 

So, I mean the lines that you specified exists in qreads.py in both the Build Tree and the Installed application locations.

**Comment by spycolyf** [comment]
Should I use the SlicerQREADS forum to resolve the other 11 remaining SlicerQREADS issues? Or will you be addressing those in time for my dev deadline? Thanks.

**Comment by jcfr** [comment]
After restarting my workstation (which end up clearing the temporary directory), I confirm that it is also failing and the following information are reported in the python interactor:

> Specified database directory '/tmp/SlicerQReads-jcfr/20210329_074610_TempDICOMDatabase' cannot be found
> Unable to open DICOM database /tmp/SlicerQReads-jcfr/20210329_074610_TempDICOMDatabase

I suspect similar information are also reported on your side, I will follow up with a fix tomorrow.

**Comment by spycolyf** [comment]
how do I run the Python Interactor? :-|

**Comment by spycolyf** [comment]
Here is the Title Info format: 

```python
slicer.util.mainWindow().windowTitle = "%s - %s" % (
    slicer.util.mainWindow().windowTitle,
    "CMRN: {PatientID}     Patient Name: {PatientName}     Study: {StudyDescription}     Series: {SeriesDescription}".format(**values))
```

**Comment by jcfr** [comment]
Thanks. I will fix the issue and integrate the relevant changes.

> re: python interactor

It can be access from the menu. See  https://github.com/KitwareMedical/SlicerQReads/issues/59#issuecomment-815175400
