### ISSUE TITLE
(Priority 3b) Update icon associated with the application

### ISSUE THREAD

**Issue by jcfr** [KitwareMedical/SlicerQReads#60]
from @spycolyf 

> 
> Here [...] is the title bar icon.
> 
> [...]
> 
> ![SlicerQREADSIconNew_Color64](https://user-images.githubusercontent.com/74066160/113080571-be62be00-919c-11eb-8989-36630142a9a5.png)

**Comment by jcfr** [comment]
@spycolyf 

Could you provide icons with the following resolutions:

* 16x16 / png
* 32x32 / png
* 64x64 / png
* 128x128 / png

along with a `.ico` file

**Comment by spycolyf** [comment]
Here are the icons I think you need in different sizes...
[SlicerQREADSIcon_128x128.zip](https://github.com/KitwareMedical/SlicerQReads/files/6259557/SlicerQREADSIcon_128x128.zip)

**Comment by spycolyf** [comment]
... ico files

[SlicerQREADSIcos_24bit.zip](https://github.com/KitwareMedical/SlicerQReads/files/6273409/SlicerQREADSIcos_24bit.zip)
[SlicerQREADSIcos_32Bit.zip](https://github.com/KitwareMedical/SlicerQReads/files/6273412/SlicerQREADSIcos_32Bit.zip)
