### ISSUE TITLE
Discuss strategy related to task allocation

### ISSUE THREAD

**Issue by jcfr** [KitwareMedical/SlicerQReads#61]
Should I use the SlicerQREADS forum to resolve the other 11 remaining SlicerQREADS issues? Or will you be addressing those in time for my dev deadline? Thanks.

_Originally posted by @spycolyf in https://github.com/KitwareMedical/SlicerQReads/issues/59#issuecomment-815256392_

**Comment by jcfr** [comment]
> Should I use the SlicerQREADS forum to resolve the other 11 remaining SlicerQREADS issues?

The Slicer forum is useful to get general guidance, reference to documentation, useful  snipped of codes. 

Generally speaking, it makes sense to engage on the forum by asking questions and formulating them independently of issue specific to this project.

For example, I moved the question specific to the window size into a dedicated post so that others in the community could easily look up information in the future. See https://discourse.slicer.org/t/how-to-set-initial-size-of-the-main-window/16991

> Or will you be addressing those in time for my dev deadline?

After prioritizing the issue, we were able to address the top three so that you could present some progress on May 30th.

Would you be able to share a calendar with relevant timelines ?

**Comment by jcfr** [comment]
Following content initially written by @spycolyf and copied from https://github.com/KitwareMedical/SlicerQReads/issues/21#issuecomment-815348499: 

> Here is my desired schedule...
>
> ASAP ................................... (Priority 3a) Update image information integrated in toolbar #59
> ASAP ................................... (Priority 3b) Update icon associated with the application #60
> Friday April 9th ............... (Priority 4) Distance measurement tool #21
> Tuesday April 13th ........ (Priority 5) Reset button #53
> Thursday April 15th ...... (Priority 6) More QREADS-like Pan and Zoom Mouse Interaction #7
> Friday April 16th ............ (Priority 7) Eliminate unnecessary widgets (see last updated comment) #33
> Tuesday April 19th ........ (Priority 8) Increase zoom presets dropdown font size #37
> Wed April 21 ...................  (A High Priority) Help Link Button #65

**Comment by spycolyf** [comment]
Is this time schedule realistic for the slicer team? If not, please propose a more feasible one.

Thanks

**Comment by jcfr** [comment]
> If not, please propose a more feasible one.

I will follow up this afternoon with an alternative schedule.

**Comment by spycolyf** [comment]
OK, thanks JC. FYI: The list above is in Priority order. If I can attempt the Help Button item that would be educational. Is that something I can implement with Python only? Shall I inquire on the SlicerQREADS forum?

**Comment by jcfr** [comment]
In short the timeline is not realistic. Now closing this issue, additional discussion will happen offline.

**Comment by spycolyf** [comment]
Hey JC, let's discuss offline. I have some ideas that will help. Some feature can wait for a later version.
