### ISSUE TITLE
Add Help Link Button

### ISSUE THREAD

**Issue by spycolyf** [KitwareMedical/SlicerQReads#65]
I am so sorry to have forgotten about this. No one will know about holding down shift for orthogonal slicing, Control and Alt for Oblique, etc. if a little help is not provided to 30,000 users, so if this can be provided, it would be essential. 

Attached below is the modified QREADS.ui and the help png icon 

![HelpImage](https://user-images.githubusercontent.com/74066160/114204623-03b28880-991f-11eb-8f38-7ffb3fc2253d.png)
[QReads.zip](https://github.com/KitwareMedical/SlicerQReads/files/6286841/QReads.zip)

Please initially set the link to Google.com and I will change it to the appropriate internal link. 

Here's a picture:

![SlicerQREADS with help button](https://user-images.githubusercontent.com/74066160/114204893-52f8b900-991f-11eb-87b1-1d0aadad3b2b.PNG)

**Comment by spycolyf** [comment]
![HelpImage](https://user-images.githubusercontent.com/74066160/114202335-b33a2b80-991c-11eb-8b89-a55227d3ce5f.png)
[QReads.zip](https://github.com/KitwareMedical/SlicerQReads/files/6286762/QReads.zip)

**Comment by jcfr** [comment]
Is this abandoned ? 

If you provide the final URL that should be associated with the browser, it should be straightforward to implement.

**Comment by spycolyf** [comment]
Pending completion and pull request from Doug
