### ISSUE TITLE
Make SlicerQREADS Pan and Zoom mouse Interaction more QREADS-like 

### ISSUE THREAD

**Issue by jcfr** [KitwareMedical/SlicerQReads#7]
Few options involving updating C++ source code:
* Commit specific to fork of Slicer used in SlicerReads.
* Improve Slicer and re-factor how mouse and keyboard control are associated with viewer.  Mapping is configurable but customization is not yet exposed. 

This is set up in `SetEventTranslationClickAndDrag`. See https://github.com/Slicer/Slicer/search?q=SetEventTranslationClickAndDrag

**Comment by spycolyf** [comment]
Reverse mouse button actions:

1) Pan with right mouse button down and drag 
2) Zoom with mouse wheel down and drag

**Comment by spycolyf** [comment]
@jcfr 

I just now discovered that when in W/L mode, pressing the left and right buttons simultaneously resets the W/L. To cut development time, let’s assign that function to the reset button.

Let me know if you have questions
