### ISSUE TITLE
Replace the SlicerQREADS Icons. 

### ISSUE THREAD

**Issue by spycolyf** [KitwareMedical/SlicerQReads#83]
@jcfr 

For the final task (I hope), please replace the SlicerQREADS icons with these brighter ones. <s>Also, the Help Button icon is necessary to changes for more QREADS-like familiarity</s>.

Thanks!

[SlicerQREADSAnd HelpButtonIcons.zip](https://github.com/KitwareMedical/SlicerQReads/files/6368016/SlicerQREADSAnd.HelpButtonIcons.zip)

**Comment by jcfr** [comment]
Issue related to Help  icon tracked in a different issue. See #85
