### ISSUE TITLE
Fix distorted DICOM Images display due to GDCM patch related to predictor6 bug in JPEG

### ISSUE THREAD

**Issue by spycolyf** [KitwareMedical/SlicerQReads#92]
See this link: https://discourse.slicer.org/t/slicer-issues-with-displaying-certain-dicom-images/17262?u=spycolyf

Images are distorted related to predictor6 bug in JPEG and GDCM patch. Images are fine in Slicer 4.13.

**Comment by spycolyf** [comment]
![image](https://user-images.githubusercontent.com/74066160/115944717-fb109500-a47c-11eb-8842-d573e778594d.png)

Apply the Slicer 4,13 fixes.

**Comment by jcfr** [comment]
Could you confirm it works with the Slicer nightly build ?

**Comment by spycolyf** [comment]
Will do. Thanks

**Comment by spycolyf** [comment]
@jcfr Yes it works!

![image](https://user-images.githubusercontent.com/74066160/115962554-92a7cf00-a4e1-11eb-8b62-1709cce1f54f.png)

**Comment by jcfr** [comment]
Great. Thanks for checking. I will work on updating the version of Slicer used in SlicerQReads.

**Comment by spycolyf** [comment]
Thanks JC!

Sent from my iPhone

On Apr 24, 2021, at 9:50 AM, Jean-Christophe Fillion-Robin ***@***.***> wrote:

﻿

Great. Thanks for checking. I will work on updating the version of Slicer used in SlicerQReads.
